const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b"},
   price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470"},
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d"},
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautiful villa.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945"},
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Treehouse Retreat",
    description: "Stay in a peaceful treehouse surrounded by nature.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4"},
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description: "Enjoy direct access to the beach from your room.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9"},
    price: 2000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Lake Cabin",
    description: "Relax by the lake in this cozy wooden cabin.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b"},
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Penthouse",
    description: "Experience luxury living with amazing city views.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd"},
    price: 3500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Swiss Chalet",
    description: "Stay in a ski-in/ski-out chalet in the Alps.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb"},
    price: 3000,
    location: "Switzerland",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge",
    description: "Enjoy wildlife in this luxury safari lodge.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e"},
    price: 4000,
    location: "Serengeti",
    country: "Tanzania",
  },
  {
    title: "Amsterdam Canal House",
    description: "Stay in a historic canal-side house.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4"},
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
  },
  {
    title: "Private Island",
    description: "Enjoy complete privacy on your own island.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972"},
    price: 10000,
    location: "Fiji",
    country: "Fiji",
  },
  {
    title: "Cotswolds Cottage",
    description: "Charming countryside cottage.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f"},
    price: 1200,
    location: "Cotswolds",
    country: "UK",
  },
  {
    title: "Boston Brownstone",
    description: "Historic home in Boston.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1533619239233-6280475a633a"},
    price: 2200,
    location: "Boston",
    country: "USA",
  },
  {
    title: "Bali Bungalow",
    description: "Beach bungalow with private pool.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938"},
    price: 1800,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Banff Cabin",
    description: "Cabin with mountain views.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb"},
    price: 1500,
    location: "Banff",
    country: "Canada",
  },
  {
    title: "Miami Apartment",
    description: "Art deco apartment in Miami.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1670963964797-942df1804579"},
    price: 1600,
    location: "Miami",
    country: "USA",
  },
  {
    title: "Phuket Villa",
    description: "Luxury tropical villa.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9"},
    price: 3000,
    location: "Phuket",
    country: "Thailand",
  },
  {
    title: "Scottish Castle",
    description: "Stay in a historic castle.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98"},
    price: 4000,
    location: "Scotland",
    country: "UK",
  },
  {
    title: "Dubai Oasis",
    description: "Luxury stay in desert.",
    image: { filename: "listingiamge",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090"},
    price: 5000,
    location: "Dubai",
    country: "UAE",
  },
  {
  title: "Paris City Apartment",
  description: "Stay in a romantic apartment near the Eiffel Tower.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34"},
  price: 2700,
  location: "Paris",
  country: "France",
},
{
  title: "Santorini Cliff House",
  description: "Enjoy stunning sea views from this cliffside home.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e"},
  price: 3500,
  location: "Santorini",
  country: "Greece",
},
{
  title: "Tokyo Capsule Stay",
  description: "Experience unique compact living in Tokyo.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1549692520-acc6669e2f0c"},
   price: 700,
  location: "Tokyo",
  country: "Japan",
},
{
  title: "Goa Beach Shack",
  description: "Relax in a cozy shack near the beach.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e"},
  price: 600,
  location: "Goa",
  country: "India",
},
{
  title: "Himalayan Cabin",
  description: "Peaceful cabin with mountain views.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470"},
  price: 900,
  location: "Manali",
  country: "India",
},
{
  title: "New Zealand Lake House",
  description: "Beautiful house near crystal clear lake.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee"},
  price: 2200,
  location: "Queenstown",
  country: "New Zealand",
},
{
  title: "Iceland Glass Igloo",
  description: "Watch northern lights from your bed.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1519681393784-d120267933ba"},
  price: 4000,
  location: "Reykjavik",
  country: "Iceland",
},
{
  title: "London Studio Flat",
  description: "Modern flat in central London.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1473959383414-b3e9e7b8bde1"},
  price: 2000,
  location: "London",
  country: "UK",
},
{
  title: "Kerala Houseboat",
  description: "Stay on water in a traditional houseboat.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429"},
  price: 1300,
  location: "Kerala",
  country: "India",
},
{
  title: "Desert Camp Rajasthan",
  description: "Experience desert life with luxury tents.",
  image: { filename: "listingiamge",
    url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470"},
  price: 800,
  location: "Jaisalmer",
  country: "India",
}
];

module.exports = { data: sampleListings };